//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Scripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Resources.Scripts", typeof(Scripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with report as (
        ///	select
        ///		shipping_county_id as county_id,
        ///		product_id,
        ///		grade as grade_id,
        ///		total_weight as weight,
        ///		product_qty as quantity
        ///	from public.account_invoice_out_report
        ///	where country_id = 235
        ///          and &quot;date&quot; between {0} and {1}
        ///          and shipping_state_id = 14
        ///          and main_categ_id in (7, 11)
        ///          and total_weight &gt; 0
        ///          and product_weight &gt; 5
        ///),
        ///counties as (
        ///	select
        ///		id as county_id,
        ///		&quot;name&quot; as county
        ///	from public.res_country_county
        ///),
        ///g [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IllinoisLargePackage {
            get {
                return ResourceManager.GetString("IllinoisLargePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with report as (
        ///	select
        ///		shipping_county_id as county_id,
        ///		product_id,
        ///		grade as grade_id,
        ///		total_weight as weight,
        ///		product_qty as quantity
        ///	from public.account_invoice_out_report
        ///	where country_id = 235
        ///          and &quot;date&quot; between {0} and {1}
        ///          and shipping_state_id = 14
        ///          and main_categ_id in (7, 11)
        ///          and total_weight &gt; 0
        ///          and product_weight &lt;= 5
        ///),
        ///counties as (
        ///	select
        ///		id as county_id,
        ///		&quot;name&quot; as county
        ///	from public.res_country_county
        ///),
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IllinoisSmallPackage {
            get {
                return ResourceManager.GetString("IllinoisSmallPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    trim(substring(par.commercial_company_name, &apos;^[^-]+&apos;)) as company,
        ///    par.city,
        ///    SUM(rep.total_weight), 
        ///    ROUND(SUM(rep.total_weight) / 2000, 2) as ustonns
        ///FROM public.account_invoice_out_report AS rep
        ///LEFT JOIN public.fertilizer_grade AS gr
        ///    ON rep.grade = gr.id
        ///LEFT JOIN public.res_partner AS par
        ///    ON rep.partner_shipping_id = par.id
        ///WHERE
        ///    rep.country_id = 235 
        ///    AND rep.date BETWEEN {0} AND {1}
        ///    AND rep.shipping_state_id = 48
        ///    AND rep.main_categ_id IN (7, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WashingtonByCompany {
            get {
                return ResourceManager.GetString("WashingtonByCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT gr.grade, ROUND(SUM(rep.total_weight) / 2000, 2) , SUM(rep.total_weight) / 2000 as Num
        ///FROM public.account_invoice_out_report AS rep
        ///LEFT JOIN public.fertilizer_grade AS gr
        ///    ON rep.grade = gr.id
        ///WHERE
        ///  rep.country_id = 235
        ///  AND rep.date BETWEEN {0} AND {1}
        ///  AND rep.shipping_state_id = 48
        ///  AND rep.main_categ_id IN (7, 11)
        ///GROUP BY 
        ///  gr.grade
        ///HAVING SUM(rep.total_weight) &gt; 0.
        /// </summary>
        public static string WashingtonByGrade {
            get {
                return ResourceManager.GetString("WashingtonByGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ROUND(SUM(rep.total_weight) / 2000, 2) , SUM(rep.total_weight) / 2000 as Num
        ///FROM public.account_invoice_out_report AS rep
        ///LEFT JOIN public.fertilizer_grade AS gr
        ///    ON rep.grade = gr.id
        ///WHERE
        ///  rep.country_id = 235  
        ///  AND rep.date BETWEEN {0} AND {1}
        ///  AND rep.shipping_state_id = 48
        ///  AND rep.main_categ_id IN (7, 11).
        /// </summary>
        public static string WashingtonTotal {
            get {
                return ResourceManager.GetString("WashingtonTotal", resourceCulture);
            }
        }
    }
}
